# --- STAGE 1: Builder Stage --
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY . . 

RUN npm run build

# --- STAGE 2: Production Stage---.
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]